export const TEXT = {
  app: {
    brandTitle: 'Smart Trans',
    brandSub: '智能交通系统',
    navDashboard: '仪表盘',
    navAccidents: '事故记录',
  },
  common: {
    all: '全部',
    yes: '是',
    no: '否',
    loading: '加载中…',
    none: '—',
  },
  dashboard: {
    title: '仪表盘',
    apiErrorTitle: '接口错误',
    apiErrorTip: '提示：请确认后端已在 28000 端口启动。',
    kpiTotal: '总记录数',
    kpiLast7d: '近 7 天',
    kpiSevere: '严重',
    pillLive: '实时',
    pillRolling: '滚动',
    regionTitle: '区域分布',
    regionMetaNone: '暂无位置数据',
    byTypeTitle: '事故类型（前 10）',
    byTypeMeta: '数量',
    severityTitle: '严重程度占比',
    severityMeta: '比例',
    timelineTitle: '近 30 天趋势',
    timelineMeta: '每日记录数',
    regionMetaFmt: (records: number, buckets: number) => `${records} 条 / ${buckets} 个分桶`,
    mapPopupFmt: (lat: string, lng: string, count: number) => `纬度 ${lat}，经度 ${lng}<br/>数量：${count}`,
  },
  accidents: {
    title: '事故记录',
    filterSeverity: '严重程度',
    filterHasAccident: '是否事故',
    filterPageSize: '每页条数',
    recordsFmt: (total: number) => `${total} 条`,
    thTime: '时间',
    thSeverity: '严重程度',
    thType: '类型',
    thConfidence: '置信度',
    thDescription: '描述',
    empty: '暂无记录',
    prev: '上一页',
    next: '下一页',
    pageFmt: (page: number, totalPages: number) => `第 ${page} / ${totalPages} 页`,
  },
  detail: {
    title: '事故详情',
    errorTitle: '错误',
    imageTitle: '图片',
    imageNone: '暂无图片。',
    recordTitle: '记录',
    copyInfo: '复制信息',
    id: 'ID',
    createdAt: '创建时间',
    hasAccidentYes: '有事故',
    hasAccidentNo: '无事故',
    description: '描述',
    cause: '事故原因',
    legalQualitative: '法律定性（参考）',
    lawRefs: '引用依据',
    hint: '提示',
    location: '地点',
    noCoordinates: '暂无坐标。',
    mapTitle: '地图',
    mapNone: '暂无位置数据可展示。',
    mapPopupFmt: (id: number, lat: string, lng: string) => `ID ${id}<br/>纬度 ${lat}，经度 ${lng}`,

    frameT0: '当前帧',
    frameT1: '事故前 1 秒',
    frameT3: '事故前 3 秒',
  },
  amap: {
    missingKey: '高德地图未配置：缺少 VITE_AMAP_KEY',
    hint: '请配置 VITE_AMAP_KEY（可选 VITE_AMAP_SECURITY_CODE）后重新构建。',
  },
}
